hyperskill_project:
  id: 420
  ide_files: https://cogniterra.org/media/attachments/lesson/34348/additional_files.json
  is_template_based: false
  use_ide: true
update_date: "Tue, 23 Jul 2024 07:43:11 UTC"
stages:
  - id: 2447
    step: 40244
    is_completed: true
  - id: 2448
    step: 40245
    is_completed: true
  - id: 2449
    step: 40246
    is_completed: false
  - id: 2450
    step: 40247
    is_completed: false
topics:
  0:
    - title: Introduction to Go
      theory_id: 17073
    - title: Comments
      theory_id: 16689
    - title: Variables and constants
      theory_id: 14468
    - title: Pointers
      theory_id: 15463
    - title: Control statements
      theory_id: 16235
    - title: Loops
      theory_id: 14707
    - title: Primitive types
      theory_id: 16871
    - title: Packages
      theory_id: 15906
    - title: Modules
      theory_id: 15970
    - title: Main (compiling and running)
      theory_id: 16128
    - title: Command-line arguments and flags
      theory_id: 17863
    - title: GoLand
      theory_id: 19072
    - title: Input/Output
      theory_id: 14527
    - title: Arrays
      theory_id: 14871
    - title: Slices
      theory_id: 15656
    - title: Working with slices
      theory_id: 15935
    - title: Strings
      theory_id: 15412
    - title: String formatting
      theory_id: 16860
    - title: Maps
      theory_id: 16999
    - title: Operations with maps
      theory_id: 17206
    - title: Compilers and interpreters
      theory_id: 13865
  1:
    - title: Structs
      theory_id: 17490
    - title: Advanced usage of structs
      theory_id: 17498
    - title: Arithmetic operations
      theory_id: 16679
    - title: Functions
      theory_id: 16388
    - title: Methods
      theory_id: 17739
    - title: Public and private scopes
      theory_id: 17514
    - title: Anonymous functions and Closures
      theory_id: 22032
    - title: Defer statement
      theory_id: 17694
    - title: Functional decomposition
      theory_id: 17506
    - title: Debugging Go code
      theory_id: 23076
    - title: Code organization. Design principles
      theory_id: 8956
    - title: Slice expressions
      theory_id: 20411
    - title: Files
      theory_id: 13025
    - title: Introduction to logging
      theory_id: 5538
    - title: Single Responsibility Principle
      theory_id: 8963
    - title: Errors
      theory_id: 16774
    - title: File types
      theory_id: 13017
    - title: Arithmetic expressions in programming
      theory_id: 17289
    - title: Advanced Input
      theory_id: 18567
    - title: Operations with strings
      theory_id: 18548
    - title: File modes and permissions
      theory_id: 13953
    - title: Working with files
      theory_id: 16498
    - title: Reading files
      theory_id: 16702
    - title: Writing data to files
      theory_id: 17627
  2:
    - title: Interfaces
      theory_id: 18727
    - title: Getting file attributes
      theory_id: 18851
    - title: Working with file paths
      theory_id: 18961
    - title: Hashing strings and files
      theory_id: 19064
    - title: Debugging Go code in GoLand
      theory_id: 23118
    - title: Working with time
      theory_id: 19297
